version: "3"

services:

  mongodb:
    image: mongo:latest
    ports:
      - "9000:27017"

  agility:
    build: ./
    container_name: agility
    environment:
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      REFRESH_TOKEN: ${REFRESH_TOKEN}
      MONGODB: mongodb://mongodb/agility
    links:
      - mongodb
    ports:
      - "7000:7000"

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "7001:8080"
    volumes:
        - ./index.html:/usr/share/nginx/html/index.html
