version: "3"

services:

  mongodb:
    image: mongo:latest
    ports:
      - "9000:27017"

  dashboard:
      image: metabase/metabase
      ports: 
        - "3000:3000"
      links:
        - mongodb

  agility:
    image: bruno1cruz/agility_deployment:latest
    container_name: agility
    environment:
      CLIENT_ID: 
      CLIENT_SECRET: 
      REFRESH_TOKEN: 
      MONGODB: mongodb://mongodb/agility
    links:
      - mongodb
    ports:
      - "7000:7000"
